services:
  - type: web
    name: DRAWBACKS
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/kratik00/DRAWBACKS
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      #- key: WEBHOOK
        #sync: false
      - key: PORT
        value: 8000  
